### ISSUE TITLE
numberToLetter() panic

### ISSUE THREAD

**Issue by adamjacobmuller** [Iwark/spreadsheet#11]
Hi,

The numberToLetter (utils.go) panic's converting the number 26 -> Z.

There's actually a bunch of panic's for some combinations:

https://play.golang.org/p/7O39c9B3JM

I was trying to think of a generic/arbitrary solution to that problem, but, didn't come up with a good one yet and I'm not sure there is one required, there is probably a column limit on google sheets.

**Comment by Iwark** [comment]
@AdamJacobMuller Thank you for the reporting!
