### ISSUE TITLE
Empty field has row 0/column 0

### ISSUE THREAD

**Issue by adamjacobmuller** [Iwark/spreadsheet#12]
```go
	for i, r := range sheet.Columns[0] {
		fmt.Printf("row %d %+v\n", i, r)
	}
```

results in:
```row 0 {Row:0 Column:0 Value:}
row 1 {Row:1 Column:0 Value:}
row 2 {Row:2 Column:0 Value:1966}
row 3 {Row:3 Column:0 Value:1967}
row 4 {Row:4 Column:0 Value:1968}
row 5 {Row:5 Column:0 Value:1969}
row 6 {Row:0 Column:0 Value:}
row 7 {Row:7 Column:0 Value:1986}
row 8 {Row:8 Column:0 Value:1987}
row 9 {Row:9 Column:0 Value:1988}
```

Note row 6

**Comment by cescoferraro** [comment]
@AdamJacobMuller what value would you expect for a empty cell other than than an empty string?

> When memory is allocated to store a value, either through a declaration or a call of make or new, and no explicit initialization is provided, the memory is given a default initialization. Each element of such a value is set to the zero value for its type: false for booleans, 0 for integers, 0.0 for floats, "" for strings, and nil for pointers, functions, interfaces, slices, channels, and maps.


https://golang.org/ref/spec#The_zero_value

**Comment by Iwark** [comment]
This issue may be about spreadsheet.v1.
Please try v2.

**Comment by adamjacobmuller** [comment]
Hi @Iwark,

This issue definitely happened for me on .v2 (https://github.com/AdamJacobMuller/tvx/blob/master/sheets.go#L9)

**Comment by adamjacobmuller** [comment]
@cescoferraro the issue here wasn't that the Value was "" (obviously that's expected/correct) but that the Row/Column are both 0.

**Comment by adamjacobmuller** [comment]
as a simple test using latest `v2`: https://gist.github.com/AdamJacobMuller/f1ad161396ba21c0dab3ddcd11b86cac

>[adam@Adams-MacBook-Pro]$ go run test.go
>Iteration 0, Row 0, Column 0, Value 'A1'
>Iteration 1, Row 1, Column 0, Value 'A2'
>Iteration 2, Row 0, Column 0, Value ''
>Iteration 3, Row 3, Column 0, Value 'A3'
>Iteration 4, Row 4, Column 0, Value 'A4'

Look at Iteration 2, obviously Value should be '', but Row should be 2, not 0

**Comment by Iwark** [comment]
@AdamJacobMuller Thanks, I'll take into that.
