### ISSUE TITLE
Unable to perform `go get gopkg.in/Iwark/spreadsheet.v2`

### ISSUE THREAD

**Issue by hachi8833** [Iwark/spreadsheet#15]
Received the following error when go-getting:

```
# cd .; git clone https://gopkg.in/Iwark/spreadsheet.v2 /Users/hachi8833/deve/golang/src/gopkg.in/Iwark/spreadsheet.v2
Cloning into '$GOPATH/src/gopkg.in/Iwark/spreadsheet.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/Iwark/spreadsheet.v2: exit status 128
```

regards,

**Comment by Iwark** [comment]
Hi, thanks for your report, and I'm sorry for the late reply.

Can you try this?

```
$ git config --global http.https://gopkg.in.followRedirects true
```

https://github.com/niemeyer/gopkg/issues/50#issuecomment-273299592

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by Iwark** [comment]
@niemeyer 
Thanks for the reporting!
I think I can close this issue now.
