### ISSUE TITLE
Create new spreadsheet ?

### ISSUE THREAD

**Issue by Gys** [Iwark/spreadsheet#18]
Hi !

Is there a reason why this package does not have a way to create a new spreadsheet ? Seems rather obvious, as updating comes after creating ? But probably I missed something ?

Thanks !

**Comment by Iwark** [comment]
Hi @Gys 
thank you for your posting.

I added a quick function to create a spreadsheet with a title.

```go
ss, err := service.CreateSpreadsheet(spreadsheet.Spreadsheet{
	Properties: spreadsheet.Properties{
		Title: "spreadsheet title",
	},
})
```

If there is any problem, please feel free to leave a comment again.
