### ISSUE TITLE
Add a property for hidden rows/columns

### ISSUE THREAD

**Issue by ghost** [Iwark/spreadsheet#19]
It would be nice to have a `hidden` property on rows and columns to be able to determine whether a particular row or column is hidden.

**Comment by Iwark** [comment]
@nyuszika7h 
Thanks,
I added `RowMetadata` and `ColumnMetadata` to `GridData`. Please take a look at e109378.

As you can see in [service_test.go](https://github.com/Iwark/spreadsheet/blob/v2/service_test.go#L48), it's a bit ugly to use, so maybe we should change `Rows` and `Columns` to some structure ( it's just an array of `Cell`s for now ).
Maybe I'll do it as next version `v3`.
