### ISSUE TITLE
Slow cell update

### ISSUE THREAD

**Issue by mcnijman** [Iwark/spreadsheet#27]
I have a spreadsheet of about 8.500 rows and 35 columns, that I have to regenerate at a certain interval.

Is there a specific reason that on every [update](https://github.com/Iwark/spreadsheet/blob/v2/sheet.go#L70) of a single cell, all cells are [regenerated](https://github.com/Iwark/spreadsheet/blob/v2/sheet.go#L121)? This gets really slow really fast..

**Comment by mcnijman** [comment]
See PR: https://github.com/Iwark/spreadsheet/pull/28

**Comment by Iwark** [comment]
Thank you ^^
