### ISSUE TITLE
How to add a new sheet?

### ISSUE THREAD

**Issue by yipjustin** [Iwark/spreadsheet#29]

**Comment by dkuebric** [comment]
@yipjustin I couldn't find a way to do this in the publicly-documented Google Sheets API: https://developers.google.com/sheets/api/reference/rest/

However, I did find a way to create multiple sheets at spreadsheet creation time, which served my purposes: https://github.com/Iwark/spreadsheet/pull/32

**Comment by zaddok** [comment]
Technically this doesn't resolve the issue.  Is a solution for this planned in the future?

**Comment by Iwark** [comment]
@zaddok 
Thank you for your reporting!
I'll take a look at it soon!

**Comment by yipjustin** [comment]
seems like it can be done thru `batchRequest` with kind `addSheet`.

see: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#addsheetrequest

**Comment by zaddok** [comment]
It would be awesome if it was added to this library.

**Comment by Iwark** [comment]
OK, it's now merged 👍 
Thanks a lot for helping guys!

https://github.com/Iwark/spreadsheet/pull/33

**Comment by zaddok** [comment]
This is great, thanks!
