### ISSUE TITLE
Why when there is an google api already ?

### ISSUE THREAD

**Issue by ghost** [Iwark/spreadsheet#35]
Does yours offer extra things ? Or a wrapper for convenience ?

See examples:

https://github.com/grokify/googleutil/blob/master/sheetsutil/v4/examples/iwark_oauth/iwark_oauth.go

**Comment by Iwark** [comment]
The first reason is that there wasn't any official package when I published this package.
Other reason is that the official one isn't so easy to use for me, but it may depend on one's personal point of view. (The code in your link doesn't compare the same function. Please try updating cells using the official package. It'll be longer than this package)

I don't know much about the official package, but there might be some extra things, too.
For example, this package automatically expand the sheet size and update cells when you are updating cells beyond the current sheet size.
