### ISSUE TITLE
How can I add a new Sheet ?

### ISSUE THREAD

**Issue by iamvon** [Iwark/spreadsheet#36]
I cannot add a new Sheet to an exist Spreadsheet. I tried add a new Sheet when follow your code:
`err = service.AddSheet(&spreadsheet, SheetProperties{
		Title: "TestAddedSheet",
		Index: 1,
})`
But it turned out an error:

> cannot use SheetProperties literal (type SheetProperties) as type spreadsheet.SheetProperties in argument to service.AddSheet

**Comment by iamvon** [comment]
Oh I can fix it simply by use `Import declarations` for the library, thank you.

**Comment by Iwark** [comment]
Nice :)
