### ISSUE TITLE
cell.Content Panic

### ISSUE THREAD

**Issue by jfyne** [Iwark/spreadsheet#9]
I am getting a panic when trying to access `cell.Content`.

`panic: runtime error: invalid memory address or nil pointer dereference`

Using your example in the README trying to read the following sheet panics

https://docs.google.com/spreadsheets/d/1pYHspti5lbnNfEv4-8ymjb8m57XwKmGo809o71oGGcg/edit#gid=0

It appears when there is a blank column. Are there any restrictions to sheets that I should be aware of?

**Comment by moorereason** [comment]
The example in the README doesn't do any error checking.  Since this package returns all cells (even empty ones), you need to make sure `cell != nil`.  See a [working example](https://github.com/moorereason/gosh2json/blob/dee6881b7354e49c1cc98f8168cb983b4720a8ce/main.go#L131).

**Comment by jfyne** [comment]
@moorereason Aha just figured that out after going through the code! Thanks

@Iwark Thanks for the library!
